language: php
php:
  - 5.2
  - 5.3
  - 5.4
before_script:
  - chmod 755 www/templates_c
  - cp www/include/config.php.example www/include/config.php
script:
  - "prove -v --exec 'php --php-ini ./tests/php.ini' ./tests/*.t"
